export const PROCEDURE_CONSUMABLE_TSV = `Procedure Category	Specific Procedure	Standard Consumables	Total Consumable Lines	Direct Material Lines
Consultation & Examination	Dental consultation	Gloves (1 pair); Face mask (1 each); Patient bib (1 each); Disinfectant wipe (2 wipes)	6	0
Consultation & Examination	Emergency dental consultation	Gloves (1 pair); Face mask (1 each); Patient bib (1 each); Disinfectant wipe (2 wipes); Cotton rolls (4 pieces)	8	0
Consultation & Examination	Follow-up consultation	Gloves (1 pair); Face mask (1 each); Patient bib (1 each); Disinfectant wipe (2 wipes)	6	0
Consultation & Examination	Implant assessment	Gloves (1 pair); Face mask (1 each); Patient bib (1 each); Disinfectant wipe (2 wipes); Cotton rolls (4 pieces)	10	2
Consultation & Examination	Oral cancer screening	Gloves (1 pair); Face mask (1 each); Patient bib (1 each); Disinfectant wipe (2 wipes); Gauze (2 pieces); Cotton rolls (4 pieces)	9	2
Consultation & Examination	Orthodontic assessment	Gloves (1 pair); Face mask (1 each); Patient bib (1 each); Disinfectant wipe (2 wipes)	10	4
Consultation & Examination	Periodontal assessment	Gloves (1 pair); Face mask (1 each); Patient bib (1 each); Disinfectant wipe (2 wipes); Cotton rolls (4 pieces)	8	0
Consultation & Examination	Routine dental check-up	Gloves (1 pair); Face mask (1 each); Patient bib (1 each); Disinfectant wipe (2 wipes)	6	0
Crowns, Bridges & Dentures	Acrylic crown	Gloves (1 pair); Face mask (1 each); Patient bib (1 each); Cotton rolls (4 pieces); Disinfectant wipe (2 wipes); Impression material or scan sleeve (1 mix/sleeve); Bite registration material (1 mix)	14	7
Crowns, Bridges & Dentures	Dental bridge	Gloves (1 pair); Face mask (1 each); Patient bib (1 each); Cotton rolls (4 pieces); Disinfectant wipe (2 wipes); Impression material or scan sleeve (1 mix/sleeve); Bite registration material (1 mix)	14	7
Crowns, Bridges & Dentures	Denture repair	Gloves (1 pair); Face mask (1 each); Patient bib (1 each); Acrylic repair resin (1 dose); Pumice/polishing material (1 portion); Disinfectant wipe (2 wipes)	8	4
Crowns, Bridges & Dentures	Flexible denture	Gloves (1 pair); Face mask (1 each); Patient bib (1 each); Impression tray (1 tray); Impression material (1 mix); Disinfectant wipe (2 wipes)	9	5
Crowns, Bridges & Dentures	Full denture	Gloves (1 pair); Face mask (1 each); Patient bib (1 each); Impression tray (1 tray); Impression material (1 mix); Disinfectant wipe (2 wipes)	9	5
Crowns, Bridges & Dentures	Metal crown	Gloves (1 pair); Face mask (1 each); Patient bib (1 each); Cotton rolls (4 pieces); Disinfectant wipe (2 wipes); Impression material or scan sleeve (1 mix/sleeve); Bite registration material (1 mix)	14	7
Crowns, Bridges & Dentures	Partial denture	Gloves (1 pair); Face mask (1 each); Patient bib (1 each); Impression tray (1 tray); Impression material (1 mix); Disinfectant wipe (2 wipes)	9	5
Crowns, Bridges & Dentures	Porcelain crown	Gloves (1 pair); Face mask (1 each); Patient bib (1 each); Cotton rolls (4 pieces); Disinfectant wipe (2 wipes); Impression material or scan sleeve (1 mix/sleeve); Bite registration material (1 mix)	14	7
Crowns, Bridges & Dentures	Zirconia crown	Gloves (1 pair); Face mask (1 each); Patient bib (1 each); Cotton rolls (4 pieces); Disinfectant wipe (2 wipes); Impression material or scan sleeve (1 mix/sleeve); Bite registration material (1 mix)	14	7
Extraction / Oral Surgery	Dry socket treatment	Gloves (1 pair); Face mask (1 each); Patient bib (1 each); Disposable suction tip (1 each); Irrigating syringe/tip (1 each); Sterile saline (1 portion/bottle); Gauze (4 pieces); Dry socket dressing (1 dose); Disinfectant wipe (2 wipes)	12	4
Extraction / Oral Surgery	Frenectomy	Sterile gloves (1 pair); Face mask (1 each); Patient bib or sterile drape (1 each); Disposable suction tip (1 each); Cotton rolls (4 pieces); Gauze (6 pieces); Local anaesthetic cartridge (1 cartridge); Dental needle (1 each); Antiseptic solution (1 dose); Sterile saline (1 portion/bottle); Disinfectant wipe (2 wipes); Surgical blade or laser tip (1 blade/tip)	13	4
Extraction / Oral Surgery	Incision and drainage of dental abscess	Sterile gloves (1 pair); Face mask (1 each); Patient bib or sterile drape (1 each); Disposable suction tip (1 each); Cotton rolls (4 pieces); Gauze (6 pieces); Local anaesthetic cartridge (1 cartridge); Dental needle (1 each); Antiseptic solution (1 dose); Sterile saline (1 portion/bottle); Disinfectant wipe (2 wipes); Surgical blade (1 blade)	14	5
Extraction / Oral Surgery	Simple extraction	Sterile gloves (1 pair); Face mask (1 each); Patient bib or sterile drape (1 each); Disposable suction tip (1 each); Cotton rolls (4 pieces); Gauze (6 pieces); Local anaesthetic cartridge (1 cartridge); Dental needle (1 each); Antiseptic solution (1 dose); Disinfectant wipe (2 wipes)	13	4
Extraction / Oral Surgery	Surgical extraction	Sterile gloves (1 pair); Face mask (1 each); Patient bib or sterile drape (1 each); Disposable suction tip (1 each); Cotton rolls (4 pieces); Gauze (6 pieces); Local anaesthetic cartridge (1 cartridge); Dental needle (1 each); Antiseptic solution (1 dose); Sterile saline (1 portion/bottle); Disinfectant wipe (2 wipes); Surgical blade (1 blade); Sutures (1 pack)	14	5
Extraction / Oral Surgery	Suture placement	Sterile gloves (1 pair); Face mask (1 each); Patient bib or sterile drape (1 each); Gauze (4 pieces); Sutures (1 pack); Antiseptic solution (1 dose); Disinfectant wipe (2 wipes)	10	3
Extraction / Oral Surgery	Wisdom tooth extraction	Sterile gloves (1 pair); Face mask (1 each); Patient bib or sterile drape (1 each); Disposable suction tip (1 each); Cotton rolls (4 pieces); Gauze (6 pieces); Local anaesthetic cartridge (2 cartridge / cartridges); Dental needle (1 each); Antiseptic solution (1 dose); Sterile saline (1 portion/bottle); Disinfectant wipe (2 wipes); Surgical blade (1 blade); Sutures (1 pack)	14	5
Fillings & Restorations	Amalgam filling	Gloves (1 pair); Face mask (1 each); Patient bib (1 each); Disposable suction tip (1 each); Cotton rolls (6 pieces); Disinfectant wipe (2 wipes); Amalgam capsule (1 capsule); Articulating paper (1 strip)	11	4
Fillings & Restorations	Composite filling	Gloves (1 pair); Face mask (1 each); Patient bib (1 each); Disposable suction tip (1 each); Cotton rolls (6 pieces); Disinfectant wipe (2 wipes); Etchant gel (1 dose); Bonding agent (1 dose); Composite material (1 unit/dose); Applicator tip/microbrush (2 pieces); Curing light sleeve (1 sleeve); Finishing/polishing strip or disc (2 pieces); Articulating paper (1 strip)	17	9
Fillings & Restorations	Core build-up	Gloves (1 pair); Face mask (1 each); Patient bib (1 each); Disposable suction tip (1 each); Cotton rolls (6 pieces); Disinfectant wipe (2 wipes); Etchant gel (1 dose); Bonding agent (1 dose); Core build-up material (1 dose); Curing light sleeve (1 sleeve); Articulating paper (1 strip)	15	7
Fillings & Restorations	Crown cementation	Gloves (1 pair); Face mask (1 each); Patient bib (1 each); Disposable suction tip (1 each); Cotton rolls (4 pieces); Disinfectant wipe (2 wipes); Dental cement (1 mix/capsule); Applicator tip/microbrush (1 each); Dental floss (1 length); Gauze (2 pieces); Articulating paper (1 strip)	12	3
Fillings & Restorations	Glass ionomer filling	Gloves (1 pair); Face mask (1 each); Patient bib (1 each); Disposable suction tip (1 each); Cotton rolls (6 pieces); Disinfectant wipe (2 wipes); Glass ionomer material (1 capsule/dose); Articulating paper (1 strip)	12	5
Fillings & Restorations	Temporary filling	Gloves (1 pair); Face mask (1 each); Patient bib (1 each); Disposable suction tip (1 each); Cotton rolls (6 pieces); Disinfectant wipe (2 wipes); Temporary filling material (1 dose); Articulating paper (1 strip)	10	1
Fillings & Restorations	Tooth bonding	Gloves (1 pair); Face mask (1 each); Patient bib (1 each); Disposable suction tip (1 each); Cotton rolls (6 pieces); Disinfectant wipe (2 wipes); Etchant gel (1 dose); Bonding agent (1 dose); Composite material (1 unit/dose); Applicator tip/microbrush (2 pieces); Curing light sleeve (1 sleeve); Finishing/polishing strip or disc (2 pieces); Articulating paper (1 strip)	13	5
Fillings & Restorations	Veneer repair	Gloves (1 pair); Face mask (1 each); Patient bib (1 each); Disposable suction tip (1 each); Cotton rolls (6 pieces); Disinfectant wipe (2 wipes); Etchant gel (1 dose); Bonding agent (1 dose); Composite material (1 unit/dose); Applicator tip/microbrush (2 pieces); Curing light sleeve (1 sleeve); Finishing/polishing strip or disc (2 pieces); Articulating paper (1 strip)	14	6
Imaging / X-rays	3D dental scan	Gloves (1 pair); Face mask (1 each); Scan sleeve (1 sleeve); Disinfectant wipe (2 wipes)	6	2
Imaging / X-rays	Bitewing X-ray	Gloves (1 pair); Face mask (1 each); Disinfectant wipe (1 wipe); X-ray sensor sleeve or X-ray film (1 sleeve/film)	5	2
Imaging / X-rays	CBCT scan	Gloves (1 pair); Face mask (1 each); Disinfectant wipe (1 wipe); Disposable bite block or bite stick cover (1 each); Chin rest/handle barrier cover (1 set)	5	1
Imaging / X-rays	Intraoral photographs	Gloves (1 pair); Face mask (1 each); Disposable cheek retractor (1 pair); Disinfectant wipe (2 wipes)	6	1
Imaging / X-rays	Occlusal X-ray	Gloves (1 pair); Face mask (1 each); Disinfectant wipe (1 wipe); Occlusal X-ray film/sensor sleeve (1 film/sleeve)	5	2
Imaging / X-rays	Panoramic X-ray / OPG	Gloves (1 pair); Face mask (1 each); Disinfectant wipe (1 wipe); Disposable bite block or bite stick cover (1 each); Chin rest/handle barrier cover (1 set)	5	1
Imaging / X-rays	Periapical X-ray	Gloves (1 pair); Face mask (1 each); Disinfectant wipe (1 wipe); X-ray sensor sleeve or X-ray film (1 sleeve/film)	5	2
Orthodontics & Stabilisation	Braces adjustment	Gloves (1 pair); Face mask (1 each); Patient bib (1 each); Disinfectant wipe (2 wipes)	10	4
Orthodontics & Stabilisation	Clear aligner review	Gloves (1 pair); Face mask (1 each); Patient bib (1 each); Disinfectant wipe (2 wipes)	9	3
Orthodontics & Stabilisation	Intermaxillary fixation / RTA-related jaw stabilisation	Sterile gloves (1 pair); Face mask (1 each); Patient bib or sterile drape (1 each); Local anaesthetic cartridge (2 cartridges); Dental needle (1 each); Arch bar/wire set (1 set); Ligature wire (6 lengths); Gauze (6 pieces); Disposable suction tip (1 each); Sterile saline (1 bottle); Antiseptic solution (1 dose); Disinfectant wipe (2 wipes)	12	4
Orthodontics & Stabilisation	Orthodontic treatment	Gloves (1 pair); Face mask (1 each); Patient bib (1 each); Cotton rolls (6 pieces); Disposable cheek retractor (1 pair); Etchant gel (1 dose); Orthodontic primer/bonding agent (1 dose); Orthodontic adhesive (1 dose); Brackets (20 pieces); Archwire (1 wire); Ligature ties (20 pieces); Applicator tip/microbrush (2 pieces); Curing light sleeve (1 sleeve); Disinfectant wipe (2 wipes)	15	8
Orthodontics & Stabilisation	Retainer fitting	Gloves (1 pair); Face mask (1 each); Patient bib (1 each); Disinfectant wipe (2 wipes); Retainer case (1 each)	9	3
Orthodontics & Stabilisation	Tooth stabilisation / splinting	Gloves (1 pair); Face mask (1 each); Patient bib (1 each); Disposable suction tip (1 each); Cotton rolls (6 pieces); Disinfectant wipe (2 wipes); Etchant gel (1 dose); Bonding agent (1 dose); Composite material (1 unit/dose); Splint wire/fibre (1 length); Applicator tip/microbrush (2 pieces); Curing light sleeve (1 sleeve); Finishing/polishing strip or disc (2 pieces)	13	6
Periodontal Procedures	Crown lengthening	Sterile gloves (1 pair); Face mask (1 each); Patient bib or sterile drape (1 each); Local anaesthetic cartridge (1 cartridge); Dental needle (1 each); Gauze (8 pieces); Disposable suction tip (1 each); Surgical blade (1 blade); Sterile saline (1 bottle); Sutures (1 pack); Periodontal dressing (1 dose); Antiseptic solution (1 dose); Disinfectant wipe (2 wipes)	13	5
Periodontal Procedures	Gingivectomy	Sterile gloves (1 pair); Face mask (1 each); Patient bib or sterile drape (1 each); Local anaesthetic cartridge (1 cartridge); Dental needle (1 each); Gauze (6 pieces); Disposable suction tip (1 each); Surgical blade or electrosurgery tip (1 blade/tip); Sterile saline (1 bottle); Antiseptic solution (1 dose); Disinfectant wipe (2 wipes)	12	4
Periodontal Procedures	Gum abscess drainage	Sterile gloves (1 pair); Face mask (1 each); Patient bib or sterile drape (1 each); Disposable suction tip (1 each); Cotton rolls (4 pieces); Gauze (6 pieces); Local anaesthetic cartridge (1 cartridge); Dental needle (1 each); Antiseptic solution (1 dose); Sterile saline (1 portion/bottle); Disinfectant wipe (2 wipes); Surgical blade (1 blade)	13	4
Periodontal Procedures	Periodontal maintenance	Gloves (1 pair); Face mask (1 each); Patient bib (1 each); Disposable suction tip (1 each); Cotton rolls (4 pieces); Disinfectant wipe (2 wipes); Polishing paste (1 portion); Prophy cup/brush (1 each)	10	3
Periodontal Procedures	Periodontal surgery	Sterile gloves (1 pair); Face mask (1 each); Patient bib or sterile drape (1 each); Local anaesthetic cartridge (1 cartridge); Dental needle (1 each); Gauze (8 pieces); Disposable suction tip (1 each); Surgical blade (1 blade); Sterile saline (1 bottle); Antiseptic solution (1 dose); Disinfectant wipe (2 wipes)	13	5
Preventive Dentistry	Deep cleaning	Gloves (1 pair); Face mask (1 each); Patient bib (1 each); Disposable suction tip (1 each); Cotton rolls (4 pieces); Disinfectant wipe (2 wipes); Gauze (4 pieces)	12	5
Preventive Dentistry	Desensitising treatment	Gloves (1 pair); Face mask (1 each); Patient bib (1 each); Disposable suction tip (1 each); Cotton rolls (4 pieces); Disinfectant wipe (2 wipes); Desensitising agent (1 dose); Applicator brush/microbrush (1 each)	9	2
Preventive Dentistry	Fissure sealant	Gloves (1 pair); Face mask (1 each); Patient bib (1 each); Disposable suction tip (1 each); Cotton rolls (4 pieces); Disinfectant wipe (2 wipes); Etchant gel (1 dose); Sealant material (1 dose); Applicator tip/microbrush (2 pieces); Curing light sleeve (1 sleeve)	11	4
Preventive Dentistry	Fluoride treatment	Gloves (1 pair); Face mask (1 each); Patient bib (1 each); Disinfectant wipe (2 wipes); Cotton rolls (4 pieces); Fluoride varnish/gel (1 dose); Applicator brush or fluoride tray (1 each/pair)	9	2
Preventive Dentistry	Oral hygiene instruction	Gloves (1 pair); Face mask (1 each); Patient bib (1 each); Disinfectant wipe (2 wipes)	8	3
Preventive Dentistry	Scaling and polishing	Gloves (1 pair); Face mask (1 each); Patient bib (1 each); Disposable suction tip (1 each); Cotton rolls (4 pieces); Disinfectant wipe (2 wipes); Polishing paste (1 portion); Prophy cup/brush (1 each)	10	3
Root Canal / Endodontics	Pulpectomy	Gloves (1 pair); Face mask (1 each); Patient bib (1 each); Rubber dam sheet (1 sheet); Disposable suction tip (1 each); Cotton rolls (6 pieces); Irrigation solution (1 portion); Endodontic irrigation needle/tip (1 each); Temporary filling material (1 dose); Disinfectant wipe (2 wipes); Endodontic files (1 set); Paper points (4 points)	15	9
Root Canal / Endodontics	Pulpotomy	Gloves (1 pair); Face mask (1 each); Patient bib (1 each); Rubber dam sheet (1 sheet); Disposable suction tip (1 each); Cotton rolls (6 pieces); Irrigation solution (1 portion); Endodontic irrigation needle/tip (1 each); Disinfectant wipe (2 wipes); Cotton pellets (4 pieces); Pulpotomy medicament/MTA (1 dose); Base/restorative cement (1 dose)	16	9
Root Canal / Endodontics	Root canal retreatment	Gloves (1 pair); Face mask (1 each); Patient bib (1 each); Rubber dam sheet (1 sheet); Disposable suction tip (1 each); Cotton rolls (6 pieces); Irrigation solution (1 portion); Endodontic irrigation needle/tip (1 each); Disinfectant wipe (2 wipes); Endodontic files (1 set); Paper points (8 points); Gutta-percha points (8 points); Root canal sealer (1 dose)	18	12
Root Canal / Endodontics	Root canal treatment	Gloves (1 pair); Face mask (1 each); Patient bib (1 each); Rubber dam sheet (1 sheet); Disposable suction tip (1 each); Cotton rolls (6 pieces); Irrigation solution (1 portion); Endodontic irrigation needle/tip (1 each); Disinfectant wipe (2 wipes); Endodontic files (1 set); Paper points (6 points); Gutta-percha points (6 points); Root canal sealer (1 dose); Cotton pellets (4 pieces)	18	11
Root Canal / Endodontics	Temporary root canal dressing	Gloves (1 pair); Face mask (1 each); Patient bib (1 each); Cotton rolls (4 pieces); Disposable suction tip (1 each); Irrigation solution (1 portion); Endodontic irrigation needle/tip (1 each); Cotton pellets (2 pieces); Intracanal medicament (1 dose); Temporary filling material (1 dose); Disinfectant wipe (2 wipes)	11	4`;
